opensciencegrid/osg-test

- osgtest/library/java.py
The output of `java -version` differs between java-1.7.0 and java-1.8.0. The former has its version number preceded by "java version" and the latter has its version preceded by "openjdk version". This commit changes `java.verify_ver()` to look for the version in the first line, ignoring any preceding text.
OpenJDK 1.7.0
```
java version "1.7.0_95"
OpenJDK Runtime Environment (rhel-2.6.4.0.el7_2-x86_64 u95-b00)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```
OpenJDK 1.8.0
```
openjdk version "1.8.0_71"
OpenJDK Runtime Environment (build 1.8.0_71-b15)
OpenJDK 64-Bit Server VM (build 25.71-b15, mixed mode)
```
> java.verify_ver does not verify java-1.8.0 (SOFTWARE-2212)

- osgtest/library/java.py
As requested by @osg-cat in #1
> Search for 'version' in output of 'java{,c} -version'

- osgtest/tests/test_06_fetch_crl.py
Also added a regex for a new verbose error message that we've been seeing on and off. I cross-checked the fetch-crl source and it appears that the additional entry is expected.
> Allow regex in fetch-crl whitelists

- osg-test
https://jira.opensciencegrid.org/browse/SOFTWARE-2306
Tests look good other than errors that are being fixed in #7: http://vdt.cs.wisc.edu/tests/20160427-1413/results.html
> osg-test should exit != 0 if tests fail (SOFTWARE-2306)

- osg-test
- osgtest/library/core.py
- osgtest/tests/special_cleanup.py
- osgtest/tests/special_selinux.py
https://jira.opensciencegrid.org/browse/SOFTWARE-2270
Pass `--selinux` to set SELinux to `enforcing` from `permissive` via `setenforce`. I spot checked the tests to verify that they're correctly enabling SELinux (or not in the first case): 
* VMU tests with SELinux disabled (default): http://vdt.cs.wisc.edu/tests/20160428-1329/results.html
* 3.3 ALL tests are due to #7, which was merged after these tests were kicked off
* Random errors appear unrelated
* VMU tests with SELinux enabled: http://vdt.cs.wisc.edu/tests/20160428-1335/results.html
* 3.3 ALL tests are due to #7, which was merged after these tests were kicked off
* EL6 CMVFS and cleanup test failures, presumably due to enabled SELinux
* EL7 HTCondor-CE, RSV, and Globus-Condor job submission failures, presumably due to enabled …
> Add option to osg-test that turns on SELinux (SOFTWARE-2270)

- osg-test
This is not intended for the May release but I figured I'd fix it before we forgot about it. Here's the good test output (other than random failures and ignored fetch-crl failures) using my branch: http://vdt.cs.wisc.edu/tests/20160502-1554/results.html
> Move exit code logic to osg-test main

- osgtest/tests/test_47_rsv.py
Successful test run [here](http://vdt.cs.wisc.edu/tests/20160523-1321/results.html).  Without GUMS, we're now running the `osg-version` and `java-version` metrics. Once we get GUMS working, we'll also be testing the `vo-supported` metric.
New RSV EL7 skip list:
```
test_050_gram_authentication_metric (osgtest.tests.test_47_rsv.TestRSV) missing globus-gatekeeper
test_052_vo_supported_metric (osgtest.tests.test_47_rsv.TestRSV) missing gums-client
test_070_switch_to_user_proxy (osgtest.tests.test_47_rsv.TestRSV) missing globus-gatekeeper
test_071_gram_authentication_with_user_proxy (osgtest.tests.test_47_rsv.TestRSV) missing globus-gatekeeper
test_072_switch_to_service_cert (osgtest.tests.test_47_rsv.TestRSV) missing globus-gatekeeper
test_074_osg_version_with_globus_job_run …
```
> Make osg-test RSV tests work with HTCondor-CE (SOFTWARE-2337)

- osgtest/tests/test_53_gums.py
Use gums-host to get the version of the GUMS server. This tests basic
HTTPS connectivity with the server that does not depend on grid
credentials or anything.
> Add GUMS server version test

- files/test_condorce_mapfile
- osg-test
- osgtest/library/core.py
- osgtest/tests/special_certs.py
- osgtest/tests/test_19_condorce.py
[SOFTWARE-1863](https://jira.opensciencegrid.org/browse/SOFTWARE-1863)
With CILogon certs: http://vdt.cs.wisc.edu/tests/20160531-1654/results.html
With DigiCert certs: http://vdt.cs.wisc.edu/tests/20160531-1656/results.html
To run osg-test using CILogon-like certs, pass the `--cilogon` option or add `cilogon = True` to the osg-test config file.
> Run osg-test with CILogon CA and certs

- osgtest/library/files.py
- osgtest/tests/test_23_gratia.py
- osgtest/tests/test_80_gratia.py
GUMS + ALL EL7 tests were [broken](http://vdt.cs.wisc.edu/tests/20160603-1216/results.html) due to the incorrect `sSLImplementation` variable in the `server.xml.template` that Gratia uses in its tomcat configuration script: it needed to be `sslImplementationName`. Curiously, GUMS on EL5 and EL6 [broke](http://vdt.cs.wisc.edu/tests/20160606-1526/results.html) unless I used `sSLImplementation`. Sigh.
The successful run is [here](http://vdt.cs.wisc.edu/tests/20160607-1646/results.html) after fixing the above and a strange requirement of the `replace_regexpr()` function where the new line had to match the regex being replaced.
Do we also need to update osg-tested-internal on EL7 to now include GUMS?
> Fix Gratia server.xml.template on EL7

- osgtest/library/core.py
Also add `core.init_dummy()` which sets `core.options` and `core._log` to
instances of DummyClass (instead of None).  This lets me import and use
osg-test modules in the interpreter or in standalone scripts, without
getting AttributeErrors because the core functions were trying to do
`_log.write()` and access options.
> Add DummyClass class that ignores everything

- osgtest/library/yum.py
- osgtest/tests/special_cleanup.py
- osgtest/tests/special_install.py
aren't picked up. Cleanup tests were also failing because of the repo change so we had to yum clean between downgrades as well.
Test results look good: http://vdt.cs.wisc.edu/tests/20160621-1642/results.html
> Yum clean before updates between OSG versions, otherwise new packages

- osgtest/library/core.py
The query run by get_package_envra() returns a missing epoch as the
string '(none)', but an RPM with no epoch is considered the same (by
rpm.labelCompare()) as having the epoch '0'. Translate so the comparison
functions work properly.
> get_package_envra: translate missing epochs to '0'

- osgtest/tests/test_25_voms_admin.py
- osgtest/tests/test_51_edgmkgridmap.py
As you can see by the entry osg-test creates in `edg.conf`, `group vomss://HOSTNAME:8443/voms/...`, that's referencing a voms-admin service, not a voms service -- those run on 15151. Therefore, the tests should require a running voms-admin webapp, not a voms server.
> edg-mkgridmap requires voms-admin, not voms

- osgtest/library/voms.py
- osgtest/tests/test_20_voms.py
- osgtest/tests/test_50_voms.py
- osgtest/tests/test_78_voms.py
This commit contains two major features:
- VOMS tests have been changed so that most of them will run without
voms-admin.
- Code for using voms (setting up a vo, adding a user, tearing down the
vo) has been moved to a separate library named `voms.py`, which can be
imported and used standalone.
By default, none of the functions require voms-admin, but two of them,
`create_vo()` and `add_user()` have a `use_voms_admin` parameter which
causes them to use the voms-admin-based code instead of the rewritten
versions. The tests take advantage of this, using voms-admin if it is
available.
Because many of the test functions have the same requirements (voms
client/server/mysql-plugin, mysql client/server, and, for EL 7, a
minimum version of voms-server), `voms.py` contains `is_installed()` and …
> Add voms library to set up a voms server without voms-admin

- files/test_sequence
- osgtest/tests/special_user.py
- osgtest/tests/test_28_gsiopenssh.py
- osgtest/tests/test_59_gsiopenssh.py
- osgtest/tests/test_92_gsiopenssh.py
The tests are one run of gsissh to see if we can connect and run a
simple command, and two runs of gsiscp to see if we can copy files
to/from the remote server.  These tests require gsi-openssh-server,
gsi-openssh-clients, and a proxy.  The code for setting up the file
transfer tests was based off of the gfal2 test code.
A more global change: I changed special_user.py to give the vdttest user
a randomly-generated password.  SSH (including GSISSH) will consider a
user 'disabled' and refuse to log in as that user if the user does not
have a valid encrypted password in /etc/shadow.
> Add tests for GSI-OpenSSH (SOFTWARE-2390)

- osgtest/library/core.py
- osgtest/tests/test_54_gratia.py
The GridftpTransferProbeDriver script (along with other items from the
gridftp-transfer probe) was replaced gridftp-transfer_meter.
It's not obvious if other changes need to be made also to the tests, but
this much at least clearly will need to be changed...
> script rename for gridftp-transfer probe (SOFTWARE-2398)

- osgtest/library/condor.py
- osgtest/library/core.py
- osgtest/tests/test_10_condor.py
- osgtest/tests/test_19_condorce.py
- osgtest/tests/test_41_jobs.py
- osgtest/tests/test_55_condorce.py
Commit messages should be descriptive enough for the small changes. Bigger changes are the added functions that:
* Wait for requested condor daemon availability
* Wait for a file to be created, which is useful for systemd lockfile generation
These changes were made to accommodate [SOFTWARE-2419](https://jira.opensciencegrid.org/browse/SOFTWARE-2419) and to eliminate the 'random' errors that would occur in HTCondor-CE's Travis-CI tests.
Test results:
[Test failures look to be random or due to the changed gridftp probe name](http://vdt.cs.wisc.edu/tests/20160826-1225/results.html)
[SL6 HTCondor-CE Travis-CI](https://travis-ci.org/brianhlin/htcondor-ce/jobs/155940747)
[SL7 HTCondor-CE Travis-CI](https://travis-ci.org/brianhlin/htcondor-ce/jobs/155940748)
> Various fixes to HTCondor-CE tests

- osgtest/tests/test_09_jobs.py
Just something I noticed when working on the CE tests. Test results look good [here](http://vdt.cs.wisc.edu/tests/20160830-1136/results.html) and I did some spot checks to make sure that the job submission tests ran as expected.
> We don't need osg-configure to run jobs, just the env files

- osgtest/tests/test_48_myproxy.py
In newer versions of Globus libs, certs that do not match the host name
of the service are rejected. Since the host cert for the machine does
not match 'localhost', we need to use the full hostname as the MyProxy
server.
This fixes the MyProxy test failures we saw with globus-gssapi-gsi-12.1.
EL6 test results are here: http://vdt.cs.wisc.edu/tests/20160831-1143/results.html
EL7 test results are pending.
> Use hostname for MyProxy tests

- osg-test
- osgtest/library/core.py
- osgtest/library/tomcat.py
- osgtest/tests/test_24_tomcat.py
- osgtest/tests/test_76_tomcat.py
[SOFTWARE-2383](https://jira.opensciencegrid.org/browse/SOFTWARE-2383)
* [With nightly=False (the default)](http://vdt.cs.wisc.edu/tests/20160906-1532/results.html) with the following failures:
* MyProxy tests failing with 3.3 testing because I didn't grab d1177fc from master
* Handful of random RHEL7 install and VM startup failures
* [With nightly=True](http://vdt.cs.wisc.edu/tests/20160906-1533/results.html) with the following failures:
* Same MyProxy and RHEL7 install failures as above
* Random Bestman/Gfal2 (1x) and EL5 SSL yum failures (4x)
Added a nightly option that will give us the flexibility to speed up tests in the future for any manual VMU runs so that developers won't have to wait as long for their results. Specifically in this change, we are disabling Tomcat persistence for …
> Improve tomcat7 startup time in VMU tests for non-nightly runs (SOFTWARE-2383)

- osgtest/tests/test_19_condorce.py
Noticed when testing [BLAHP #47](https://github.com/osg-bosco/BLAH/pull/47)
> Ensure that PBS jobs cannot match to the condor backend

- osgtest/library/service.py
- osgtest/tests/test_11_condor_cron.py
- osgtest/tests/test_88_condor_cron.py
Use systemctl commands for starting/stopping condor-cron. In addition, determine the status of the process by using `systemctl is-active` on EL 7 and `service ... status` on EL 6, instead of looking for a lock file. This fixes errors caused by the removal of the condor-cron init script in SOFTWARE-2439.
The results of a VMU test run are here: http://vdt.cs.wisc.edu/tests/20160921-0857/packages.html
> Fix condor-cron start/stop to work with systemd

- osgtest/library/condor.py
- osgtest/library/service.py
- osgtest/tests/test_10_condor.py
- osgtest/tests/test_11_condor_cron.py
- osgtest/tests/test_12_gatekeeper.py
- osgtest/tests/test_15_xrootd.py
- osgtest/tests/test_16_rsv.py
- osgtest/tests/test_17_pbs.py
- osgtest/tests/test_19_condorce.py
- osgtest/tests/test_20_voms.py
- osgtest/tests/test_22_myproxy.py
- osgtest/tests/test_26_bestman.py
- osgtest/tests/test_41_jobs.py
- osgtest/tests/test_54_gratia.py
- osgtest/tests/test_55_condorce.py
- osgtest/tests/test_76_tomcat.py
- osgtest/tests/test_77_myproxy.py
- osgtest/tests/test_78_voms.py
- osgtest/tests/test_79_condorce.py
- osgtest/tests/test_83_rsv.py
- osgtest/tests/test_84_xrootd.py
- osgtest/tests/test_87_gatekeeper.py
- osgtest/tests/test_88_condor_cron.py
- osgtest/tests/test_89_condor.py
- osgtest/tests/test_90_bestman.py
- osgtest/tests/test_91_pbs.py
This fixes the globus-gatekeeper startup issues in the tests. A rather large set of changes as it moves almost all ([GridFTP has a broken response to `status`](https://jira.opensciencegrid.org/browse/SOFTWARE-2470?filter=12359)) tests to the new service commands; I'd suggest reviewing commit by commit as the files changed are mostly exclusive to and grouped by commits. Let me know if there are any questions at all.
Test results: http://vdt.cs.wisc.edu/tests/20160928-1353/results.html
> Fully support systemd in the service library

- osgtest/tests/test_19_condorce.py
- osgtest/tests/test_41_jobs.py
- osgtest/tests/test_55_condorce.py
Update tests are broken because `htcondor-ce-2.0.8-2` unconditionally restarts on uninstallation so the CE tests see that the service is already running and subsequent CE tests are skipped. The service restart is a temporary fix (required to reload the `condor_mapfile` to accept our daemons using the generated host cert) to be removed when `htcondor-ce-2.0.9-3` is released so that we don't have a blind spot in the test coverage while it is in testing.
Test results: http://vdt.cs.wisc.edu/tests/20160929-1113/results.html
> Temporary fix to handle broken CE 2.0.8 to 2.0.9 updates

- osgtest/tests/test_51_edgmkgridmap.py
There was an error in the nightlies because `edg-mkgridmap` failed to actually generate a grid-mapfile:
```======================================================================
ERROR: test_02_edg_mkgridmap (osgtest.tests.test_51_edgmkgridmap.TestEdgMkGridmap)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/usr/lib/python2.6/site-packages/osgtest/library/osgunittest.py", line 165, in run
testMethod()
File "/usr/lib/python2.6/site-packages/osgtest/tests/test_51_edgmkgridmap.py", line 44, in test_02_edg_mkgridmap
contents = files.read(os.environ['GRIDMAP'], True)
File "/usr/lib/python2.6/site-packages/osgtest/library/files.py", line 38, in read
the_file = open(path, 'r')
IOError: [Errno 2] No such file or directory: …
```
> Check if edg-mkgridmap actually generates the grid-mapfile

- osgtest/tests/test_13_gridftp.py
- osgtest/tests/test_42_gridftp.py
- osgtest/tests/test_43_uberftp.py
- osgtest/tests/test_86_gridftp.py
This requires the version of gridftp that was just released today, because of the init script exit status fix.
Test results are here: http://vdt.cs.wisc.edu/tests/20161108-1537/packages.html
> Use service library for gridftp and add badskips if it can't be started

- osgtest/tests/test_12_gatekeeper.py
Saw the following error in the nightlies:
```
ERROR: test_01_stop_gatekeeper (osgtest.tests.test_87_gatekeeper.TestStopGatekeeper)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/osgtest/library/osgunittest.py", line 165, in run
testMethod()
File "/usr/lib/python2.7/site-packages/osgtest/tests/test_87_gatekeeper.py", line 11, in test_01_stop_gatekeeper
self.skip_ok_unless(core.state['globus-gatekeeper.started-service'], 'did not start gatekeeper')
KeyError: 'globus-gatekeeper.started-service'
```
Test results look good here (some random, unrelated failures): http://vdt.cs.wisc.edu/tests/20161109-1412/results.html
> Always define globus-gatekeeper.started-service state

- osgtest/tests/test_12_gatekeeper.py
- osgtest/tests/test_17_pbs.py
- osgtest/tests/test_41_jobs.py
- osgtest/tests/test_55_condorce.py
- osgtest/tests/test_91_pbs.py
Test results here: http://vdt.cs.wisc.edu/tests/20161129-0935/results.html
The PBS server startup test started being "skipped" when we replaced the `core.system()` call to stop the service with `service.stop()`*, which doesn't start the service unless we set `core.state['pbs_server.started-service'] = True`**. We didn't have a complete PBS blind spot in the tests because the `condor_ce_trace_pbs` jobs seemed to run fine...
\* We stopped the service because we had to run `service pbs create` to create the initial config and it did a bad job of stopping the service afterwards, which we needed to do to drop additional config (maybe?).
** We really shouldn't be setting `core.state` variables in our library functions, at the very least, not the `<service name>.started-service` keys because it …
> Fix pbs server start

- osgtest/library/tomcat.py
- osgtest/tests/test_24_tomcat.py
... instead of "catalina.CYMD.log".
Ran a test run against it, which looks good:
http://vdt.cs.wisc.edu/tests/20161209-1405/packages.html
> configure tomcat to use "catalina.log" (SOFTWARE-2547)

- files/test_sequence
- osgtest/library/core.py
- osgtest/library/mysql.py
- osgtest/tests/special_install.py
- osgtest/tests/test_07_munge.py
- osgtest/tests/test_10_condor.py
- osgtest/tests/test_17_pbs.py
- osgtest/tests/test_19_condorce.py
- osgtest/tests/test_24_tomcat.py
- osgtest/tests/test_29_slurm.py
- osgtest/tests/test_54_gratia.py
- osgtest/tests/test_55_condorce.py
- osgtest/tests/test_74_slurm.py
- osgtest/tests/test_91_pbs.py
- osgtest/tests/test_94_munge.py
Test results [here]( http://vdt.cs.wisc.edu/tests/20161214-1435/results.html); failures, although festive, are unrelated.
This set of commits:
* Separates out the munge service setup since it's required by both PBS and SLURM tests
* Installs slurm from osg-contrib if we're running 'All*' tests
* Fixes a mysql.is_running bug and PBS startup bug that I noticed when testing
* Added get_stat() function to handle missing files. This was duplicated throughout the tests before the function.
@osg-cat: I don't think this needs much of a review, assign as you see fit.
> Test HTCondor-CE + Slurm interaction in automated tests (SOFTWARE-2421)

- osgtest/library/java.py
- osgtest/tests/test_04_java.py
- osgtest/tests/test_97_java.py
Previous formatting of java alternatives:
```
*+ 1           /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.111-2.6.7.2.el7_2.x86_64/jre/bin/java
```
CentOS/RHEL 7 appear to have changed their java alternatives format to the following:
```
*+ 1           java-1.8.0-openjdk.x86_64 (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-2.b15.el7_3.x86_64/jre/bin/java)
2           java-1.7.0-openjdk.x86_64 (/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.121-2.6.8.0.el7_3.x86_64/jre/bin/java)
```
Here's a run with failing java selection (CentOS and RHEL 7 BeStMan and GUMS tests) : http://vdt.cs.wisc.edu/tests/20161212-1621/results.html
Here's a run with the fix (I excluded 'All*' tests with the hope they'd finish earlier): http://vdt.cs.wisc.edu/tests/20161213-1542/results.html
I also removed the unused libraries from the …
> Handle different alternatives formats

- osgtest/tests/test_17_pbs.py
- osgtest/tests/test_41_jobs.py
- osgtest/tests/test_55_condorce.py
- osgtest/tests/test_91_pbs.py
Vaguely SOFTWARE-2484 related.
Apparently some (non-epel, oops) flavors of the torque/pbs packages have
a little different layout, and, for instance, 'torque-mom' is actually a
virtual capability provided by the 'torque-client' rpm.  In that case,
we really only care about 'torque-mom' as a dependency, not necessarily
as a package name.
> allow virtual dependencies for torque packages

- osgtest/tests/special_install.py
Python docs claim that `OrderedDict` was added in Python 2.7 but it appears to be available in python core on all the Python 2.6 installations I've looked at (osghost, fermicloud VMs, my laptop, Carl's CSL machine).
@edquist: I added you as a requested reviewer since we were talking about `OrderedDict`.
> Maintain order of package list specified by param files

- osgtest/tests/test_41_jobs.py
@edquist: Requesting that you look this over since you wrote the `core.__run_command()` timeout stuff. Should be a short review. 
`condor_*run` will patiently wait for jobs to complete even if the job has no chance of completing. Utilize Carl's timeout option to `core.check_system()` to avoid TIMEOUT failures.
Before this commit: http://vdt.cs.wisc.edu/tests/20170109-1206/results.html
After this commit: http://vdt.cs.wisc.edu/tests/20170118-1100/results.html
> Limit condor_{ce_,}run tests to 10 minutes

- osgtest/tests/test_18_cvmfs.py
Test results clean across the board: http://vdt.cs.wisc.edu/tests/20170119-1552/results.html
> Use the default CVMFS cache location to avoid SELinux failures

- osgtest/tests/test_55_condorce.py
Slurm names are different across EL versions
> Fix slurm service check on EL7

- .travis.yml
- travis-ci/setup_tests.sh
- travis-ci/test_inside_docker.sh
Since we're limited to 5 concurrent builds and we're kicking so many off, we should make sure that we set the opensciencegrid/osg-test travis-ci limit to 2 builds at a time.
> Travis-CI support (SOFTWARE-2313)

- osgtest/tests/test_19_condorce.py
- osgtest/tests/test_79_condorce.py
`htcondor-ce-condor` just provides config for `htcondor-ce` and the `condor` backend. Installing `htcondor-ce` brings all the actual packages necessary for testing CE -> condor job submission; we already throw down half of the necessary config by writing our own job routes, so we just need to add the backend `condor` configuration
> Don't depend on htcondor-ce-condor

- osgtest/tests/test_49_jobs.py
We already dropped the creation of the job env files in 840ea8
Tests without this commit: http://vdt.cs.wisc.edu/tests/20170417-1748/results.html
Tests with the commit: http://vdt.cs.wisc.edu/tests/20170418-1146/results.html
> Drop job env backup cleanup dependence on osg-configure

- osgtest/tests/special_install.py
Dependencies + available EPEL versions caused updates to fail.
Fixed test results here: http://vdt.cs.wisc.edu/tests/20170531-1348/results.html
> Remove bestman2-server-dep-libs in updates to OSG 3.4

- bootstrap-osg-test
- osgtest/library/yum.py
- osgtest/tests/special_cleanup.py
- osgtest/tests/special_install.py
- osgtest/tests/test_12_gatekeeper.py
- osgtest/tests/test_24_tomcat.py
- osgtest/tests/test_30_misc.py
- osgtest/tests/test_76_tomcat.py
Test results here: http://vdt.cs.wisc.edu/tests/20170531-1316/results.html. osg-gridftp install failures are because I messed up the param file by telling it to install the "osg-gridftp (Java) package". Upgrade failures in 3.4 are due to not having the bestman uninstallation test merged into this branch.
I can kick off a 3.3 osg-gridftp if you want to double check that
> Drop EL5 and 3.1 codepaths

- .travis.yml
- osgtest/tests/test_13_gridftp.py
- osgtest/tests/test_14_lcmaps.py
- osgtest/tests/test_15_xrootd.py
- osgtest/tests/test_19_condorce.py
- osgtest/tests/test_44_glexec.py
- osgtest/tests/test_55_condorce.py
- osgtest/tests/test_79_condorce.py
- osgtest/tests/test_84_xrootd.py
- osgtest/tests/test_85_lcmaps.py
- osgtest/tests/test_86_gridftp.py
This adds testing of the LCMAPS VOMS plugin to the nightlies, replacing the gridmap auth we were testing before. Other things to note:
* The suite still tests `edg-mkgridmap`and `glexec` individually.
* Force GSI auth in HTCondor-CE to ensure that the LCMAPS auth gets exercised. Before it would just fallback to FS auth.
* I'm not sure if XRootd + LCMAPS auth gets exercised (my guess is it doesn't) but added the env variables anyway
> LCMAPS VOMS plugin tests

- osgtest/tests/test_19_condorce.py
Write our own based on the core CE mapfile. Fixing the tests as part of the project to separate the OSG bits from the CE
> Handle separate CE map files

- osgtest/tests/special_selinux.py
- osgtest/tests/test_28_gsiopenssh.py
- osgtest/tests/test_59_gsiopenssh.py
- osgtest/tests/test_92_gsiopenssh.py
On EL7, SELinux forbids sshd (and gsisshd) from opening unregistered ports (e.g. 2222). This fix allows gsisshd to use port 2222 for the duration of the osg-test run. Some contortions were necessary so that the tests OkSkip if we need policycoreutils-python and can't find it.
> Fix SELinux issues with gsi-openssh tests

- osgtest/tests/test_47_rsv.py
the vo-supported-probe is dropped from rsv 3.15.0
> drop test_052_vo_supported_metric (SOFTWARE-2763)

- osgtest/tests/special_install.py
Test results are good: http://vdt.cs.wisc.edu/tests/20171117-1442/results.html
> Grab slurm from development repos instead of contrib (SOFTWARE-2994)

- README.md
- osg-test
- osgtest/library/core.py
- osgtest/tests/special_certs.py
In conjuction with https://github.com/opensciencegrid/osg-ca-generator/pull/9
> Remove options to specify cilogon-type certs (now the default)

- osg-test-log-viewer
- osgtest/library/core.py
- osgtest/library/osgunittest.py
- osgtest/tests/special_install.py
- osgtest/tests/test_21_gums.py
- osgtest/tests/test_26_bestman.py
- osgtest/tests/test_51_edgmkgridmap.py
- osgtest/tests/test_52_bestman.py
- osgtest/tests/test_53_gums.py
- osgtest/tests/test_75_gums.py
- osgtest/tests/test_90_bestman.py
this allows test classes to add decorators like:
```
@osgrelease(3.3)
def test_foo_33_only(self):
...
```
or
```
@osgrelease(3.3, 3.4)
def test_foo_33_or_34(self):
...
```
to restrict running a particular test function to when the currently installed osg release series is in the provided list.
`@osgrelease(3.3)` is added for the bestman tests, as an example, but the other `skip_ok_unless_installed()`'s still need to be reviewed for 3.3-only packages.
> decorators to tests to osg release series (SOFTWARE-2759)

- osgtest/library/core.py
- osgtest/tests/test_58_gfal2util.py
As part of [SOFTWARE-2911](https://jira.opensciencegrid.org/browse/SOFTWARE-2911). I added the decorators to the bestman only for 3.3. But also I added some more tests with gfal. Finally since I was already there I picked of @edquist work and added the decorator for Major OS versions to exclude.
The [VMU tests ](http://vdt.cs.wisc.edu/tests/20180125-1905/results.html) are green.
> SOFTWARE-2911

- osg-test-log-viewer
- rpm/osg-test.spec
Tested with Python 2 and Python 3.4 on Fermicloud VMs, and Python 2.7 and 3.6 on my Fedora 28 laptop.
> Python 3 compatibility for osg-test-log-viewer

- osgtest/library/core.py
- osgtest/tests/test_29_slurm.py
- osgtest/tests/test_74_slurm.py
osg-test test changes in order to use slurm 17.  Last VMU results: 
http://vdt.cs.wisc.edu/tests/20180716-1750/results.html
> osg-test changes for SOFTWARE-3202

- osgtest/tests/test_47_rsv.py
VMU tests are mostly green with the failures due to the installs where the REUNA-ca CRL is missing:
http://vdt.cs.wisc.edu/tests/20180727-1746/results.html
> Add crl and ca cert probe tests

- osgtest/tests/test_47_rsv.py
Changes to allow test to pass if metric returns a warning, VMU is green. 
http://vdt.cs.wisc.edu/tests/20180730-2008/results.html 
Also, added a sleep in the test run on fermicloud and deleted crl files to force the metric to give a warning and the test still passed.
> Ca probes sw 3322 - allow warning status

- osgtest/tests/test_14_lcmaps.py
- osgtest/tests/test_15_xrootd.py
rather than adding an xrootd_policy section to lcmaps.db
This would break due to an argument parsing bug in xrootd-lcmaps < 1.4.0
> set xrootd-lcmaps policy in sec_protocol (SOFTWARE-3396)

- osgtest/tests/test_14_lcmaps.py
- osgtest/tests/test_15_xrootd.py
Followup to #132 - @brianhlin says that since 3.3 and EL6 tests are backversioned on xrootd-lcmaps, we want to restore the old behavior for `xrootd-lcmaps < 1.4.0`.
> conditionalize xrootd policy based on lcmaps version (SOFTWARE-3396)

- osgtest/tests/test_14_lcmaps.py
We only want to add this xrootd_policy section to lcmaps.db for
xrootd-lcmaps < 1.4.0, that is, skip if xrootd-lcmaps >= 1.4.0
Also, per Mat's suggestion, i am renaming the name of the test to
say that it is for the "old" xrootd_policy
...
Soon we'll add a more clear helper to do package version checks.
> Fix direction of version comparison (SOFTWARE-3396)

- osgtest/tests/test_06_fetch_crl.py
Example: http://vdt.cs.wisc.edu/tests/20181022-0423/126/osg-test-20181022.log
> Add LWP error to fetch-crl whitelist (cause of EL7 errors)

- osgtest/tests/test_100_condor.py
This error sometimes caused Condor shutdown to raise an exception.
> Fix missing key in Condor startup

- osgtest/library/core.py
apparently `cmp()` and `__cmp__()` go away in python3, so you have to implement the other operators yourself.
@matyasselmeci said he wanted python3 support in osg-test, even now.
In fact you can't even get the python3 versions of the rpm modules (`rpm` and `rpmUtils`) on rhel7 + epel7, with python3 installed.  Mat said It can be done (tm) on fedora; so Mat, i'll leave it to you to test this.
As you can see, this non-`__cmp__` based sorting was trivial to add, but (as i also said to Mat when he bugged me about this), Why the python folks found cmp-based ordering so religiously objectionable that they removed it from the language is beyond me.
> python3 support for PackageVersion, for Mat

- osgtest/tests/test_380_cvmfs.py
singularity 3.0.2 gets rid of the singularity-runtime package, but provides it in the singularity base package
> make singularity-runtime check by dependency (SOFTWARE-3532)

- osg-test-log-viewer
The most user-visible change is that `systemctl is-active` and `service ... status` commands are no longer highlighted in red if they return non-zero. Also has some fixes for error handling.
> Fixes for osg-test-log-viewer

- osgtest/tests/test_158_xrootd_tpc.py
- osgtest/tests/test_465_xrootd_tpc.py
- osgtest/tests/test_838_xrootd_tpc.py
The setUp method gets used for all the other test functions so common excludes/skip_oks can be placed there instead of being duplicated.
> Don't run xrootd-tpc tests on EL6 and also factor out common 'xrootd' dependency

- .travis.yml
- osgtest/library/core.py
- osgtest/tests/special_install.py
- travis-ci/gridftp.packages
- travis-ci/htcondor-ce.packages
- travis-ci/setup_tests.sh
- travis-ci/singularity.packages
- travis-ci/stashcache.packages
- travis-ci/test_inside_docker.sh
- travis-ci/xrootd.packages
This at least gives us minimal test coverage while we're having local Gluster issues
> Initial OSG 3.5 support, including Travis tests (SOFTWARE-3783)

- osgtest/tests/test_290_slurm.py
This fixes Slurm setup errors from our [nightlies](http://vdt.cs.wisc.edu/tests/20190820-0423/results.html) [1]. Clean run here: http://vdt.cs.wisc.edu/tests/20190819-1329/results.html
[1]
```
======================================================================
ERROR: test_01_slurm_config (osgtest.tests.test_290_slurm.TestStartSlurm)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/osgtest/library/osgunittest.py", line 196, in run
testMethod()
File "/usr/lib/python2.7/site-packages/osgtest/tests/test_290_slurm.py", line 72, in test_01_slurm_config
chmod=0o644)
File "/usr/lib/python2.7/site-packages/osgtest/library/files.py", line 105, in write
dir=os.path.dirname(path))
File …
```
> Fix Slurm config location

- osgtest/tests/special_install.py
Upon release of OSG 3.5.0, this list does not need to contain osg-development
3.5 osg-tested-internal clean install failures that showed up in the nightlies are gone with this commit: http://vdt.cs.wisc.edu/tests/20190820-0912/results.html
> Include osg-development to satisfy reqs for osg-tested-internal

- osgtest/tests/test_290_slurm.py
We could instead build Slurm with './configure
--sysconfdir=/etc/slurm' (the default is /etc) but I'd like to
minimize the differences between the upstream packaging
> Use /etc for the Slurm sysconfdir (SOFTWARE-3783)

- .travis.yml
- osgtest/tests/test_150_xrootd.py
- osgtest/tests/test_450_xrootd.py
- osgtest/tests/test_840_xrootd.py
- travis-ci/osg-xrootd-standalone.packages
- travis-ci/test_inside_docker.sh
I can revert the changes in the `.travis.yml` parameters once we're ready to merge. CI passes for osg-xrootd-standalone package sets and the former xrootd package sets: https://travis-ci.org/brianhlin/osg-test/builds/575047482
> Use osg-xrootd-standalone in our XRootD tests (SOFTWARE-3520)

- osgtest/tests/special_install.py
- Remove 3.5.0 pre-release hack that was added in '198d85488a342fdb206d9044b4a51cef71bb9d9f'
> Fix osg-tested-internal repos

- osgtest/tests/test_150_xrootd.py
- osgtest/tests/test_840_xrootd.py
Noticed when testing osg-xrootd-standalone in SOFTWARE-3587: when
XRootD is installed, the service starts but doesn't get configured. We
decided that service startup, client tests, and service stop should
have unified base requirements.
> Require globus-proxy-utils for XRootD service mgmt

- osgtest/tests/test_580_gfal2util.py
(SOFTWARE-4073)
I think this plus the SLURM PR that just got merged are the only changes we need to make the tests marked EL7-only also run on EL8. In most places we used `>= 7` or already has `8` in the `@core.elrelease` decorator.
> Enable some other EL8 tests

- osgtest/tests/test_155_stashcache.py
Solves the same problem for osg-test that https://github.com/opensciencegrid/docker-xcache/pull/43 and https://github.com/opensciencegrid/docker-xcache/pull/44 solve for the containers.
> Make scitokens.conf file for tests

- osgtest/tests/test_190_condorce.py
`core.get_stat` returns `None` if the file doesn't exist and `condor.wait_for_daemon` handles `None` stats by looking for the relevant sentinel starting at the beginning of the file. Things look pretty good here: https://osg-sw-submit.chtc.wisc.edu/tests/20201028-0817/results.html
> HTCondor starts up too fast in 8.9.9 and we miss the schedd startup

- osgtest/tests/test_190_condorce.py
We don't use the stat if the CE service was started outside of osg-test
> Move the stat after the initial service check

- osgtest/library/mysql.py
- osgtest/tests/special_install.py
- osgtest/tests/test_290_slurm.py
- osgtest/tests/test_740_slurm.py
Test results here: https://osg-sw-submit.chtc.wisc.edu/tests/20210325-1148/packages.html. 3.6 `slurm_trace` tests fail because the 3.6 blahp is broken but this otherwise fixes all the other Slurm startup failures we're seeing in the nightlies
> Update Slurm tests for Slurm 20 (SOFTWARE-4446)

- osgtest/tests/test_190_condorce.py
In HTCondor-CE 5.1.0 we're going to be forcing users to wrap the 2nd field in the mapfile with `/` if they want them to be regex (added in https://github.com/htcondor/htcondor-ce/pull/425) and this has been causing our HTCondor-CE EL7 osg CI tests to fail. This fixes that failure (run here: https://github.com/brianhlin/htcondor-ce/actions/runs/712664940).
N.B. the EL8 osg failure seems to be real issue where the client seems to be segfaulting
> Add new condor mapfile syntax

- osgtest/tests/test_550_condorce.py
Also consolidated `condor_ce_trace` calls into a single function
Works here: https://github.com/brianhlin/BLAH/runs/2273292248?check_suite_focus=true#step:7:1340
> Dump CE held job reasons

- osgtest/tests/test_190_condorce.py
We'll just bump the version number in the HTCondor-CE repo instead
since it's on the verge of release anyway
> Fix the version check for mapfile config.d

- osgtest/tests/test_550_condorce.py
This does not appear to work with an impending version of the blahp:
1. The cache format changed to "<jobid> <hex pickle>"
2. Trace jobs complete too quickly to be picked up by the new caching
mechanism, at least for Slurm. Perhaps because the query command
changed from scontrol -> squeue.
> Drop brittle check ensuring blahp queries filled the cache

- osgtest/tests/test_150_xrootd.py
(SOFTWARE-4599)
Example tests are part of https://osg-sw-submit.chtc.wisc.edu/tests/20210505-1714/packages.html (see the "XRootD" package set).
> Use new config for newer versions of xrootd-multiuser

- osgtest/tests/test_465_xrootd_tpc.py
This has been broken with XRootD 5 for a long time, but multistream TPC is not a common OSG use case
This reverts commit c4d10e044fd1a56a144cb2085c7b19baef827cf9.
> Revert "The testing should include multistream"

- osgtest/tests/special_install.py
SOFTWARE-4607.
Test results: https://osg-sw-submit.chtc.wisc.edu/tests/20210608-1549/packages.html
(the 3.6 build doesn't have the patch for [HTCONDOR-512](https://opensciencegrid.atlassian.net/browse/HTCONDOR-512) but actual installation succeeded)
> Special case: enable mod_auth_oidc module for htcondor-ce-collector on EL8

- osgtest/tests/test_465_xrootd_tpc.py
Note: this doesn't solve any test failures, just gives us a better error message.
(SOFTWARE-4604)
> Fix KeyError in TPC tests if macaroon creation failed (SOFTWARE-4604)

- osgtest/tests/test_410_jobs.py
- osgtest/tests/test_550_condorce.py
Token discovery details: https://zenodo.org/record/3937438. Support was added for this to `condor_submit` in 9.0.2 and is expected in 9.1.3. I'm working on making use of this in `condor_ce_run` and adding token discovery to `condor_ce_trace`
> Use BEARER_TOKEN_FILE env var to specify the token path

- osgtest/library/core.py
- osgtest/library/service.py
Compare https://osg-sw-submit.chtc.wisc.edu/tests/20210903-2358/results.html
to a nightly run https://osg-sw-submit.chtc.wisc.edu/tests/20210904-0423/results.html
doesn't look much different in the raw logs but if you're doing a manual run with --df (to dump output into a separate file) or are looking at the output with osg-test-log-viewer, it's nice not to have it cluttered up with a ton of "rpm --query" and "systemctl is-active" calls.
> Don't print output for some system calls

- osgtest/tests/test_460_stashcache.py
- osgtest/tests/test_580_gfal2util.py
Test results here https://osg-sw-submit.chtc.wisc.edu/tests/20210922-0855/packages.html. EL8 failures are expected because only `python3-gfal2-util` is available on EL8 and it doesn't provide `gfal2-util`
> Account for new gfal2-util package split (SOFTWARE-4825)

- osgtest/tests/test_401_scitokens.py
https://osg-sw-submit.chtc.wisc.edu/tests/20211005-1035/packages.html
> Get rid of the inner json.dumps() when constructing the payload for demo.scitokens.org

- osgtest/library/core.py
- osgtest/library/voms.py
- osgtest/tests/test_200_voms.py
- osgtest/tests/test_407_voms.py
Some tests (even in OSG 3.6) need grid proxies which we can get with
voms-proxy-init if grid-proxy-init is not available.
Also do some cleanup and defensive coding for VOMS.
> Use voms-proxy-init to get grid proxies if needed

- osgtest/library/core.py
- osgtest/library/voms.py
- osgtest/tests/test_200_voms.py
- osgtest/tests/test_407_voms.py
Reverts opensciencegrid/osg-test#243
> test_09_basic_grid_proxy (osgtest.tests.test_407_voms.TestVOMS) None
> Revert "Use voms-proxy-init to get grid proxies if needed"

- osgtest/library/core.py
- Change environ_context to set multiple environment variables
- Add no_x509 context manager for temporarily moving the user's x509 credentials out of the way
- Add core.no_bearer_token() context manager for testing without a token
> More context managers

- osgtest/tests/special_user.py
- osgtest/tests/test_407_voms.py
Same objective as #243 except not broken. This time it checks if a user cert/key is available and doesn't try to make the proxy if it isn't (okskip).
I also have tests this time: https://osg-sw-submit.chtc.wisc.edu/tests/20211102-1152/packages.html
I replaced 'globus-proxy-utils' with 'voms-clients-cpp' in all the parameters files for this test. TPC failed to start because the config file was only created if globus-proxy-utils is installed -- obviously that only happens with this param set and is fixed in my branch anyway.
> Use voms-proxy-init to get certs attempt 2

- osgtest/tests/test_410_jobs.py
- osgtest/tests/test_550_condorce.py
(SOFTWARE-4901)
Until 9.0.8, HTCondor requires GSI for proxy delegation so job
submission failed using HTCondor-CE client tools with a proxy.
Marking as `do-not-merge` as I haven't tested these changes.
> Test HTCondor-CE job sub w/o X.509 for unsupported HTCondor versions

- osgtest/tests/test_060_fetch_crl.py
Alternatively we could just ignore `^VERBOSE\(0\)` since it's informational.
> Add some more fetch-crl warnings to the ignore list

- osgtest/library/core.py
- osgtest/tests/special_install.py
Per SOFTWARE-5060:
- Make this test understand virtual dependencies.
- For each dependency, run rpm -q --whatprovides $dependency
which will tell you which of the installed RPMs satisfy that
dependency.
- If none of them do (nonzero exit code), fail;
- if one of them does, verify that one;
- if multiple of them do, verify the first one.
Note, we provide a new alternate version of `dependency_is_installed` in `core` called `dependency_installed_rpms`, which does the same thing but returns a list of installed rpms matching a dependency rather than just the bool result.
> allow rpm verifying virtual dependencies (SOFTWARE-5060)

- osgtest/tests/test_465_xrootd_tpc.py
since it would be useful if a mismatch means the output is garbage, truncated, or empty.
> Compare and print source/destination file sizes for XRootD-TPC tests

- osgtest/library/voms.py
voms-proxy-fake is the same thing. Do ths for now as a bandaid to get tests moving
I figured it's best to just get this in with a loud `FIXME` commit instead of blocking on me
> FIXME: EPEL9 voms doesn't include voms-proxy-direct

- osgtest/tests/test_290_slurm.py
The old config resulted in errors like the following in slurm.log:
```
[2023-03-27T04:49:43.934] error: cannot read
/cgroup/system.slice/slurmd.service/cgroup.controllers: No such file or
directory
```
Success here https://osg-sw-submit.chtc.wisc.edu/tests/20230328-1359/results.html
> Use default cgroup location, /sys/fs/cgroup (SOFTWARE-5500)

- README.md
- files/test_sequence
- osgtest/tests/test_055_osg_ca_manage.py
- osgtest/tests/test_060_fetch_crl.py
- Add new integration test to be run before fetch_crl that installs CAs via `osg-ca-manage`
- Add more descriptive error for fetch_crl tests
> SOFTWARE-5618: add test for osg-ca-manage

- osgtest/library/files.py
- osgtest/tests/special_cleanup.py
- osgtest/tests/special_install.py
(orig. title was "Do not erase osg-release before upgrading")
It is not necessary and breaks packages that depend on osg-release like osg-update-vos.
> Fix cleanup failures when using osg-update-data (since it depends on osg-release)

- osgtest/tests/special_install.py
This was causing EL9 test failures for the central collector:
- Before: https://osg-sw-submit.chtc.wisc.edu/tests/20230921-1431/results.html
- After: https://osg-sw-submit.chtc.wisc.edu/tests/20230921-1736/results.html
> mod_auth_oidc is now available in appstream on EL8/9 (SOFTWARE-5679)

- osgtest/tests/test_155_stashcache.py
- osgtest/tests/test_460_stashcache.py
- osgtest/tests/test_835_stashcache.py
- travis-ci/stashcache.packages
- The `pelican-osdf-compat` RPM doesn't provide the `stashcache-client` virtual dependency; it's a very old name (used for the Python version of `stashcp`) so check for the `osdf-client` virtual dependency instead when deciding whether to skip the `stashcp` test or not
- Pelican uses `STASH_TOPOLOGY_NAMESPACE_URL` instead of `STASH_NAMESPACE_URL` for the URL to the namespaces JSON; set both in the environment so old and new versions of `stashcp` work as expected
- Better detect if we're using a Go version of `stashcp` (and should pass `--cache` instead of editing `caches.json`)
> Get stashcp tests working with Pelican

- osgtest/tests/test_155_stashcache.py
- osgtest/tests/test_460_stashcache.py
- osgtest/tests/test_835_stashcache.py
- travis-ci/stashcache.packages
The dependency "osdf-client" is not available, except in 23-upcoming.
VMU run: https://osg-sw-submit.chtc.wisc.edu/tests/20240207-1110/packages.html. A spot check showed that the various "stashcache" tests are no longer getting skipped in the XCache test set.
> Require "stashcp" for stashcp tests (SOFTWARE-5812)

- osgtest/tests/test_460_stashcache.py
Pelican 7.5.0+ talks to the Director by default, not Topology, so the fake Topology server we're setting up in the tests gets bypassed. Setting STASH_USE_TOPOLOGY to non-blank makes it fall back to the previous behavior.
https://osg-sw-submit.chtc.wisc.edu/tests/20240208-1718/packages.html
> Set STASH_USE_TOPOLOGY for stashcp tests for Pelican 7.5.0+ compat

- osgtest/tests/test_155_stashcache.py
As of that ticket, we need grid-mapfiles in /run/stash-origin-auth and /run/stash-cache-auth. They are normally downloaded from Topology, but we don't hit topology in these tests.
Example run: https://osg-sw-submit.chtc.wisc.edu/tests/20240411-1529/packages.html
> Write grid-mapfiles for stashcache tests (SOFTWARE-5846)

- osgtest/tests/test_150_xrootd.py
`scitokens.trace debug` only turned on 'debug' messages, not 'error', 'warning', and 'info'
> Fix scitokens debug level

- osgtest/tests/special_install.py
- Code to convert `23` to `23-main` already existed in the "upgrade" logic, but was missing from the "downgrade" logic
- It might make more sense to remove the special casing and switch the parameters.d/*.yaml files to include `-main`, this might have wider code ramifications though
- eg. `sources: [opensciencegrid:main; 23-main; osg, osg-upcoming > 24/osg-minefield]`
Successful test run using this patch: https://osg-sw-submit.chtc.wisc.edu/tests/20241024-1623/results.html
> Add 2X-main special casing to install

- osgtest/tests/test_155_stashcache.py
- osgtest/tests/test_460_stashcache.py
- osgtest/tests/test_835_stashcache.py
"stash-cache" and "stash-origin" are deprecated (and have been removed in 24-main),
and the "pelican" command-line tool does not work with the osg-test
stashcache setup because it uses a director instead of topology.
At some point, separate tests for pelican should be added.
> Skip StashCache tests if pelican is installed

- files/test_sequence
- osg-test
- osgtest/tests/special_user.py
- osgtest/tests/test_080_certs.py
Move `special_certs.py` to `test_080_certs.py` to circumvent an issue with the test cert getting overwritten prior to being used by `test_055_osg_ca_manage.py:test_01_setup_ca`
> SOFTWARE-6152: reorder cert generation

- files/test_sequence
- osgtest/tests/test_295_htvault.py
- osgtest/tests/test_980_htvault.py
Basic "install and start" VMU test for HTVault. Creates the necessary config files and key pair then attempts to start the systemd service. Has been tested once: https://osg-sw-submit.chtc.wisc.edu/tests/20250730-1140/results.html
> SOFTWARE-6174: HTvault tests

- osgtest/library/core.py
- osgtest/tests/special_install.py
- osgtest/tests/test_055_osg_ca_manage.py
Primarily dropping the deprecated unittest.assertEquals() call and redoing how we test for the presence of the osg-release RPM (or whatever provides it).  Also some cleanup of Python 2-isms and type warnings.
> Various OSG 25/EL 10 fixes
