osgtest/tests/test_12_gatekeeper.py
osgtest/tests/test_54_gratia.py

@brianhlin can your please review this? I manually tested on a vm and it works fine.

SOFTARE-2293 execute condor_meter without gram

---

osg-test

Verified the fixes on an EL5 test VM.

Fixed issues with non-zero exit code

---

files/test_sequence

Test results look good here: http://vdt.cs.wisc.edu/tests/20160502-1014/results.html

Run gfal2util tests before gums/condor

---

osg-test

Test results here: http://vdt.cs.wisc.edu/tests/20160502-1029/results.html
Logs are back!

Fix bug that caused missing test logs for successful runs

---

osgtest/tests/special_cleanup.py
osgtest/tests/special_selinux.py

Requested in https://jira.opensciencegrid.org/browse/SOFTWARE-2270 (I believe, can't tell because Jira's down atm).

Use verbose setenforce command arguments

---

files/test_sequence
osgtest/library/tomcat.py
osgtest/tests/test_23_gratia.py
osgtest/tests/test_24_tomcat.py
osgtest/tests/test_25_voms_admin.py
osgtest/tests/test_50_voms.py
osgtest/tests/test_53_gums.py
osgtest/tests/test_54_gratia.py
osgtest/tests/test_76_tomcat.py

http://vdt.cs.wisc.edu/tests/20160602-1452/results.html
Test results (look good): http://vdt.cs.wisc.edu/tests/20160602-1452/results.html

Fix detection of Tomcat startup in osg-test

---

osg-test

This lets me comment out tests to I can easily disable them temporarily and reenable them later.

Allow comments and blank lines in test_sequence

---

osgtest/tests/test_04_java.py
osgtest/tests/test_24_tomcat.py

Test results [here](http://vdt.cs.wisc.edu/tests/20160801-1419/results.html)

Improve tomcat7 startup time in VMU tests (SOFTWARE-2383)

---

osgtest/tests/test_41_jobs.py
osgtest/tests/test_55_condorce.py

JIRA: https://jira.opensciencegrid.org/browse/SOFTWARE-2450
Results: http://vdt.cs.wisc.edu/tests/20160929-1044/results.html

Verify that the PBS blahp cache is populated

---

osgtest/library/mysql.py
osgtest/library/service.py
osgtest/tests/test_10_condor.py
osgtest/tests/test_11_condor_cron.py
osgtest/tests/test_12_gatekeeper.py
osgtest/tests/test_15_xrootd.py
osgtest/tests/test_16_rsv.py
osgtest/tests/test_17_pbs.py
osgtest/tests/test_19_condorce.py
osgtest/tests/test_20_voms.py
osgtest/tests/test_22_myproxy.py
osgtest/tests/test_24_tomcat.py
osgtest/tests/test_26_bestman.py
osgtest/tests/test_28_gsiopenssh.py
osgtest/tests/test_55_condorce.py
osgtest/tests/test_76_tomcat.py
osgtest/tests/test_77_myproxy.py
osgtest/tests/test_78_voms.py
osgtest/tests/test_79_condorce.py
osgtest/tests/test_83_rsv.py
osgtest/tests/test_84_xrootd.py
osgtest/tests/test_87_gatekeeper.py
osgtest/tests/test_88_condor_cron.py
osgtest/tests/test_89_condor.py
osgtest/tests/test_90_bestman.py
osgtest/tests/test_91_pbs.py
osgtest/tests/test_92_gsiopenssh.py

@matyasselmeci I've made the changes that you mentioned in #45. Automated test results: http://vdt.cs.wisc.edu/tests/20161024-1711/results.html

Refactor systemd support

---

osgtest/tests/test_76_tomcat.py
osgtest/tests/test_84_xrootd.py

http://vdt.cs.wisc.edu/tests/20161026-1030/results.html

Verify tomcat gets stopped and add xrootd/voms-admin TODOs

---

osgtest/library/condor.py
osgtest/tests/test_10_condor.py
osgtest/tests/test_19_condorce.py
osgtest/tests/test_55_condorce.py

https://jira.opensciencegrid.org/browse/SOFTWARE-2479
Automated testing results here: http://vdt.cs.wisc.edu/tests/20161028-1017/results.html

Add HTCondor-CE-View test 

---

Makefile

Package osg-test-log-viewer

---

osgtest/tests/test_54_gratia.py
osgtest/tests/test_80_gratia.py

Results look good here: http://vdt.cs.wisc.edu/tests/20170405-1016/results.html

Drop BDII-related tests

---

osgtest/library/files.py
osgtest/tests/test_24_tomcat.py
osgtest/tests/test_76_tomcat.py

Provide runtime JSP implementation for Tiles

---

.travis.yml
travis-ci/setup_tests.sh
travis-ci/test_inside_docker.sh

And make sure we install the necessary packages to actually test gridftp

Add ability to specify multiple pkgs for installation in Travis CI

---

osgtest/tests/test_58_gfal2util.py

Change asked per @brianhlin request and Travis came out fine:
https://travis-ci.org/efajardo/osg-test/jobs/253708754

Changed the package to skip ok on the gridftp tests

---

.travis.yml
osgtest/tests/test_19_condorce.py
travis-ci/setup_tests.sh
travis-ci/test_inside_docker.sh

Also, fix location of CE `condor_mapfile` if we don't generate a hostcert

Run 3.4 Travis-CI tests by default

---

osgtest/library/service.py
osgtest/tests/test_11_condor_cron.py
osgtest/tests/test_19_condorce.py
osgtest/tests/test_26_bestman.py

Plus bonus commit for TODO item that wasn't marked as such.
Test results here: http://vdt.cs.wisc.edu/tests/20170810-0913/results.html

Limit status checks before starting services (SOFTWARE-2846)

---

README.md

https://twiki.opensciencegrid.org/bin/view/SoftwareTeam/TestingFramework

Convert TestingFramework TWiki doc

---

README.md

https://twiki.opensciencegrid.org/bin/view/Documentation/Release3/AutomatedTests

Convert AutomatedTests

---

files/test_sequence
osgtest/tests/test_03_haveged.py
osgtest/tests/test_24_tomcat.py
osgtest/tests/test_76_tomcat.py
osgtest/tests/test_98_haveged.py

http://vdt.cs.wisc.edu/tests/20170927-1122/packages.html

Use HAVEGED to add entropy (SOFTWARE-2880)

---

osgtest/library/core.py
osgtest/library/files.py
osgtest/library/voms.py
osgtest/tests/special_cleanup.py
osgtest/tests/test_06_fetch_crl.py
osgtest/tests/test_10_condor.py
osgtest/tests/test_11_condor_cron.py
osgtest/tests/test_13_gridftp.py
osgtest/tests/test_14_lcmaps.py
osgtest/tests/test_15_xrootd.py
osgtest/tests/test_18_cvmfs.py
osgtest/tests/test_19_condorce.py
osgtest/tests/test_21_gums.py
osgtest/tests/test_24_tomcat.py
osgtest/tests/test_30_misc.py
osgtest/tests/test_35_osg_configure.py
osgtest/tests/test_38_cvmfs.py
osgtest/tests/test_42_gridftp.py
osgtest/tests/test_43_uberftp.py
osgtest/tests/test_44_glexec.py
osgtest/tests/test_45_xrootd.py
osgtest/tests/test_52_bestman.py
osgtest/tests/test_53_gums.py
osgtest/tests/test_58_gfal2util.py
osgtest/tests/test_80_gratia.py
osgtest/tests/test_82_cvmfs.py
osgtest/tests/test_86_gridftp.py

http://vdt.cs.wisc.edu/tests/20170928-1321/packages.html

Various misc cleanup tasks

---

osgtest/tests/test_84_xrootd.py

http://vdt.cs.wisc.edu/tests/20171016-1317/results.html

check_stop xrootd (SOFTWARE-2513)

---

osgtest/tests/test_54_gratia.py
osgtest/tests/test_80_gratia.py

Due to remote server failures
results here: http://vdt.cs.wisc.edu/tests/20171025-0920/results.html

Drop dCache storage probe (SOFTWARE-2955)

---

osgtest/tests/test_21_gums.py
osgtest/tests/test_53_gums.py
osgtest/tests/test_75_gums.py

We still test it against the CE in 3.3 -> 3.4 update tests

Restore GUMS tests in 3.4

---

osgtest/tests/test_13_gridftp.py
osgtest/tests/test_14_lcmaps.py
osgtest/tests/test_15_xrootd.py
osgtest/tests/test_19_condorce.py
osgtest/tests/test_45_xrootd.py
osgtest/tests/test_79_condorce.py
osgtest/tests/test_84_xrootd.py
osgtest/tests/test_86_gridftp.py

Test results: http://vdt.cs.wisc.edu/tests/20180216-1059/packages.html
Should be merged alongside: https://github.com/opensciencegrid/vm-test-runs/pull/56

Test xrootd-lcmaps with the LCMAPS VOMS plugin (SOFTWARE-3134)

---

files/test_sequence

Test results look good here: http://vdt.cs.wisc.edu/tests/20180219-1636/results.html

Move all proxy generation tests to the beginning of actual testing

---

osgtest/tests/test_47_rsv.py

Just removing a bit of useless junk.

Code cleanup

---

osg-test
osgtest/library/core.py
osgtest/library/files.py
osgtest/library/osgunittest.py
osgtest/library/voms.py
osgtest/tests/special_cleanup.py
osgtest/tests/special_user.py
osgtest/tests/test_05_mysqld.py
osgtest/tests/test_09_jobs.py
osgtest/tests/test_15_xrootd.py
osgtest/tests/test_18_cvmfs.py
osgtest/tests/test_19_condorce.py
osgtest/tests/test_20_voms.py
osgtest/tests/test_21_gums.py
osgtest/tests/test_22_myproxy.py
osgtest/tests/test_23_gratia.py
osgtest/tests/test_26_bestman.py
osgtest/tests/test_28_gsiopenssh.py
osgtest/tests/test_29_slurm.py
osgtest/tests/test_41_jobs.py
osgtest/tests/test_42_gridftp.py
osgtest/tests/test_43_uberftp.py
osgtest/tests/test_45_xrootd.py
osgtest/tests/test_47_rsv.py
osgtest/tests/test_52_bestman.py
osgtest/tests/test_54_gratia.py
osgtest/tests/test_58_gfal2util.py
osgtest/tests/test_80_gratia.py

VMU results are here: http://vdt.cs.wisc.edu/tests/20180828-1006/packages.html

Fix obvious Python 3 incompatibilities

---

bootstrap-osg-test

I don't particularly care about the installing from RPM case

Update bootstrap-osg-test to fetch from source control (SOFTWARE-2232)

---

bootstrap-osg-test

The OSG release ver gets populated by positional arg with these changes. Bonus commit for minimizing the git clone sizes

Fix bootstrap-osg-test (SOFTWARE-2232)

---

osgtest/tests/test_10_condor.py
osgtest/tests/test_89_condor.py

To address changes in HTCondor 8.8.0

Setup personal condor (SOFTWARE-3473)

---

osgtest/tests/test_150_xrootd.py
osgtest/tests/test_450_xrootd.py
osgtest/tests/test_840_xrootd.py

These seem to work just fine, no need to disable them. I don't know what the original problem was.
Test results: http://vdt.cs.wisc.edu/tests/20181211-0909/packages.html

Re-enable and fix up xrootd-fuse tests

---

.travis.yml
osgtest/tests/test_155_stashcache.py

http://vdt.cs.wisc.edu/tests/20190802-1624/results.html

Support XCache 1.1 (SOFTWARE-3561)

---

osgtest/tests/test_410_jobs.py
osgtest/tests/test_550_condorce.py

Related: https://github.com/opensciencegrid/vm-test-runs/pull/94

Some HTCondor-CE tests really require a proxy

---

osgtest/tests/test_280_gsiopenssh.py
osgtest/tests/test_550_condorce.py

Here's a test with new results: https://osg-sw-submit.chtc.wisc.edu/tests/20200722-1404/results.html

Fix various errors from https://osg-sw-submit.chtc.wisc.edu/tests/20200722-1126/packages.html

---

osgtest/tests/test_290_slurm.py
osgtest/tests/test_740_slurm.py

Fix slurm service name on EL8

---

osgtest/tests/test_380_cvmfs.py

And some bonus whitespace fixups

Non-root Singularity tests (SOFTWARE-3911)

---

osgtest/tests/test_180_cvmfs.py
osgtest/tests/test_380_cvmfs.py
osgtest/tests/test_820_cvmfs.py

A bunch of helpful stuff that was added to debug the CVMFS EL6 failures, More or less the same as what ran here minus a few specific debug commits: https://osg-sw-submit.chtc.wisc.edu/tests/20201015-1225/results.html.

Modernize CVMFS tests

---

osgtest/tests/test_465_xrootd_tpc.py

The testing should include multiple streams

The testing should include multistream

---

files/test_sequence
osgtest/tests/test_190_condorce.py
osgtest/tests/test_401_scitokens.py
osgtest/tests/test_410_jobs.py
osgtest/tests/test_550_condorce.py
osgtest/tests/test_790_condorce.py

And other miscellaneous HTCondor-CE test cleanups

Add scitokens tests (SOFTWARE-4221)

---

osgtest/tests/special_user.py

This allows pre-generation of the test user. Also move verification to before the user cert generation.
Works here: https://github.com/brianhlin/BLAH/runs/2270379720?check_suite_focus=true#step:7:67

Separate out user cert generation and addition to the grid-mapfile

---

osgtest/library/condor.py
osgtest/library/files.py
osgtest/library/java.py
osgtest/library/osgunittest.py
osgtest/library/service.py
osgtest/library/yum.py
osgtest/tests/test_460_stashcache.py

This does a BadSkip if one of the listed services is not running.

Move skip_bad_unless_running() out of test_460_stashcache.py since it's more generally useful

---

osgtest/library/core.py
osgtest/library/voms.py
osgtest/tests/test_150_xrootd.py
osgtest/tests/test_158_xrootd_tpc.py
osgtest/tests/test_200_voms.py
osgtest/tests/test_401_scitokens.py
osgtest/tests/test_407_voms.py
osgtest/tests/test_450_xrootd.py
osgtest/tests/test_465_xrootd_tpc.py
osgtest/tests/test_780_voms.py
osgtest/tests/test_838_xrootd_tpc.py

Test xrootd with multiple authentication methods, including VOMS

---

osgtest/tests/test_550_condorce.py

To troubleshoot HTCondor-CE 6 CI failures

Moar ce debugging

---

osgtest/tests/test_380_cvmfs.py
osgtest/tests/test_410_jobs.py
osgtest/tests/test_550_condorce.py

grep for '3.' didn't really turn up much of interest

Prepare for OSG 23 (SOFTWARE-5679)

---

osgtest/library/core.py

This should reduce huge log files due to overly verbose commands.

Trim command output

---

osgtest/tests/test_295_htvault.py

Per Dave D, the daemon user changed from `vault` to `openbao` in 2.1.0 https://opensciencegrid.atlassian.net/browse/SOFTWARE-6198

Accomodate change in daemon user for htvault-config
